{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingressName }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.paths.pathHome.path }}
            pathType: {{ .Values.paths.pathHome.pathType }}
            backend:
              service:
                name: {{ .Values.serviceName }} 
                port: 
                  number: {{ .Values.service.port }}
          - path: {{ .Values.paths.pathChar.path }}
            pathType: {{ .Values.paths.pathChar.pathType }}
            backend:
              service:
                name: {{ .Values.serviceName }} 
                port: 
                  number: {{ .Values.service.port }}
          - path: {{ .Values.paths.pathHealth.path}}
            pathType: {{ .Values.paths.pathHealth.pathType }}
            backend:
              service:
                name: {{ .Values.serviceName }} 
                port: 
                  number: {{ .Values.service.port }}
{{- end -}}