apiVersion: v1
kind: Service
metadata:
  name: rick-and-morty-app-service 
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080  
  selector:
    app: {{ .Chart.Name }}