apiVersion: v1
kind: Service
metadata:
  name: rick-and-morty-service
spec:
  selector:
    app: rick-and-morty-rest-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
